### ISSUE TITLE
Playbook sends Command to the remote devices one letter at a time.

### ISSUE THREAD

**Issue by awizzl** [joelwking/ansible-ios#1]
`HostName1# ### Thu Oct 27 03:10:01 2016 10.228.255.14 ###
[
% Bad IP address or host name% Unknown command or computer name, or unable to find computer address
HostName1#'
% Bad IP address or host name% Unknown command or computer name, or unable to find computer address
HostName1#s
% Type "show ?" for a list of subcommands
HostName1#h
Help may be requested at any point in a command by entering
a question mark '?'.  If nothing matches, the help list will
be empty and you must backup until entering a '?' shows the
available options.
Two styles of help are provided:
1. Full help is available when you are ready to enter a
   command argument (e.g. 'show ?') and describes each possible
   argument.
2. Partial help is provided when an abbreviated argument is entered
   and you want to know what arguments match the input
   (e.g. 'show pr?'.)

HostName1#o
% Incomplete command.

HostName1#w
% No connections open
HostName1#
HostName1#r
% No open connections
HostName1#u
undebug
% Incomplete command.

HostName1#n
% Ambiguous command:  "n"
HostName1#n
% Ambiguous command:  "n"
HostName1#i
% Incomplete command.

HostName1#n
% Ambiguous command:  "n"
HostName1#g`

**Comment by joelwking** [comment]
It uses Paramiko / SSH and this is the expected behavior.  Here is a good link explaining what you observed. 

**http://blog.hyfather.com/blog/2013/04/18/ssh-uses-four-tcp-segments-for-each-character/**

**Comment by awizzl** [comment]
Thanks for your response. Specifying the type for the `command` dict in this module as a list fixed the issue.

From:
`commands=dict(required=True)`
To:
`commands=dict(type='list',required=True)`
